Nordix/xcluster

ovl-index.md
ovl/usrsctp/.gitignore
ovl/usrsctp/README.md
ovl/usrsctp/default/bin/usrsctp_test
ovl/usrsctp/default/etc/init.d/11xnet.rc
ovl/usrsctp/default/etc/init.d/20usrsctp.rc
ovl/usrsctp/default/etc/kubernetes/usrsctp/usrsctp-svc.yaml
ovl/usrsctp/default/etc/kubernetes/usrsctp/usrsctp-test.yaml
ovl/usrsctp/image/Dockerfile
ovl/usrsctp/image/default/etc/init.d/42usrsctpt.rc
ovl/usrsctp/image/default/etc/init.d/99main.rc
ovl/usrsctp/image/tar
ovl/usrsctp/network-topology/Envsettings
ovl/usrsctp/src/Makefile
ovl/usrsctp/src/lib/ipaddr.c
ovl/usrsctp/src/lib/ipaddr.h
ovl/usrsctp/src/lib/log.c
ovl/usrsctp/src/lib/log.h
ovl/usrsctp/src/lib/stats.c
ovl/usrsctp/src/lib/stats.h
ovl/usrsctp/src/lib/test/throttler-test.c
ovl/usrsctp/src/lib/throttler.c
ovl/usrsctp/src/lib/throttler.h
ovl/usrsctp/src/usrsctpt/cmdClient.c
ovl/usrsctp/src/usrsctpt/cmdNonInteractiveClient.c
ovl/usrsctp/src/usrsctpt/cmdServer.c
ovl/usrsctp/src/usrsctpt/main.c
ovl/usrsctp/tar
ovl/usrsctp/usrsctp.sh

Test environment for
https://datatracker.ietf.org/doc/draft-porfiri-tsvwg-sctp-natsupp/
A copy of sctp ovl with some changes:
- Do not modprobe sctp kmod
- usrsctpt test tool for a minimal server/client based on https://github.com/sctplab/usrsctp
- Only K8s test with 2 VMs, 2 routers and a tester connected for a distributed SCTP client in k8s connected to the SCTP server in the tester VM in a multipath scenario

ovl/usrsctp: Experiments with userspace SCTP stack

---

ovl/k8s-cni-calico/README.md
ovl/k8s-cni-calico/calico-orig.yaml
ovl/k8s-cni-calico/default/etc/kubernetes/load/calico.yaml
ovl/k8s-cni-calico/ipv4/etc/kubernetes/load/calico.yaml
ovl/k8s-cni-calico/ipv6/etc/kubernetes/load/calico.yaml

This PR updates the calico version to v3.22.0, and also enables the optional floating IP feature.
Needed for testing https://github.com/projectcalico/calico/issues/5198
The previous PR (https://github.com/Nordix/xcluster/pull/19) had to be closed due to some mistakes on my part.

ovl/k8s-cni-calico: Bump version to v3.22.0

---

Envsettings

Some distros (I am using WSL2) don't allow accessing /proc using non-root users inside non-root network namespaces, ps -p seems a safer bet to check if we are running bash. Maybe this is just a problem with WSL2, anyhow it would be nice to fix this.
```
sriramy@DESKTOP-D5JSVGC-wsl:~/xc/xcluster$ readlink -f /proc/$$/exe
/usr/bin/bash
sriramy@DESKTOP-D5JSVGC-wsl:~/xc/xcluster$ echo $?
0
sriramy@DESKTOP-D5JSVGC-wsl:~/xc/xcluster$ exec ip netns exec sriramy_xcluster1 /bin/bash
bash-5.0$ readlink -f /proc/$$/exe
bash-5.0$ echo $?
1
```

"cdo" completion: Use ps -p $$ instead of /proc/$$/exe

---

xcluster.sh

I would like to add an option --kpatch to "xc kernel_build" command to provide a kernel patch on the fly.
Yet another good to have PR, no hurry to review/merge.

xc: Add option for kernel patches before build

---

ovl/images/images.sh

Signed-off-by: Szilard Vincze <szilard.vincze@est.tech>
When we share the same local registry between xcluster and kind, images.sh does not work because it finds two IP addresses since kind connects the registry to its own network too.
With this fix, cmd_get_regip() will return only the first IP instead of two in a row and images.sh can be used for both xcluster and kind.

Use the first IP address if there are more.

---

ovl/test/default/usr/lib/xctest
xcluster.sh

The ipv6 addresses on the xcluster bridges uses $xcluster_PREFIX, but that variable is lost when "sudo" is invoked. This means that the default `1000::1` is always used, which will not match the addresses in the VMs if another PREFIX is used.
And BTW, `1000::1` is not a good prefix, `fd00:` [is better](https://en.wikipedia.org/wiki/Unique_local_address).

Include $xcluster_PREFIX when creating netns

---

ovl/iptools/README.md
ovl/iptools/iptools.sh
ovl/iptools/tar

Not urgent, but I will work some with `nft` and would like to use the latest.
The shift .bz2 -> .xz makes this PR a bet more complex than expected. Also the `iptools.sh man` is updated so the man-pages for nft are included.
`hping3` is included if it exist on the host + some doc updates.

ovl/iptools: upgrade to nft 1.0.7

---

ovl/k8s-cni-cilium/README.md
ovl/k8s-cni-cilium/default/etc/kubernetes/load/quick-install.yaml

Cilium have been stuck on v1.11 for a long time, but it was a new config param to helm that was needed:
```
--set securityContext.privileged=true
```
It took me a day to `git bisect` this. The env can become useful for future troubleshooting, please see [ovl/x-cilium](https://github.com/uablrek/xcluster-ovls/blob/main/x-cilium/README.md).

ovl/k8s-cni-cilium: upgrade to v1.14.0

---

ovl/load-balancer/default/etc/init.d/20load-balancer.rc
ovl/load-balancer/ecmp/etc/init.d/50ecmp.rc
ovl/load-balancer/load-balancer.sh

Linux-5.4.35 was hard-coded to cover an ECMP problem that should be exposed

ovl/load-balancer: Honor PREFIX and use the configured kernel

---

ovl/k8s-cni-calico/tar
xcadmin.sh

The check in `xcadmin.sh` for ovl/k8s-xcluster fails and must be removed

Remove check for ovl/k8s-xcluster in k8s_build_images

---

ovl/network-topology/README.md
ovl/network-topology/backend/etc/init.d/11xnet.rc
ovl/network-topology/bridge/etc/init.d/11xnet.rc
ovl/network-topology/diamond/etc/init.d/11xnet.rc
ovl/network-topology/dual-path/etc/init.d/11xnet.rc
ovl/network-topology/evil_tester/etc/init.d/11xnet.rc
ovl/network-topology/multihop/etc/init.d/11xnet.rc
ovl/network-topology/multilan-router/etc/init.d/11xnet.rc
ovl/network-topology/multilan/etc/init.d/11xnet.rc
ovl/network-topology/network-topology.sh
ovl/network-topology/x-diamond/etc/init.d/11xnet.rc
ovl/network-topology/xnet/etc/init.d/11xnet.rc

The setup scripts matched on vm-0* which excluded the range vm-100--vm-199 as valid VMs. Also some minor test and doc fixes

ovl/network-topology: Allow >vm-099 and fix tests

---

ovl/kubernetes/default/etc/init.d/31kube-master.rc

Fix some minor bugs in 31kube-master.rc that prevented multi-masters from working
With this PR multi-master seem to work in [ovl/k8s-ha](https://github.com/uablrek/xcluster-ovls/blob/main/k8s-ha/README.md) (redundant etcd is not yet implemented though).

ovl/kubernetes: Fix multi-masters

---

image/rootfs/init

Nothing exotic, just:
```sh
if ! test -r /run/initialboot; then
date > /run/initialboot
```
IMHO, this is better than out-calls from the VMs to qemu. A test that _wants_ a re-unpack can delete the file.
Fixes #53

Don't re-unpack the cdrom on reboot

---

config/busybox-1.36.1
xcluster.sh

Adds functions for stop qemu emulation and reset+continue. The intention is for test-cases that tests things while a VM is away (rebooting). Since xcluster VMs reboot in about 1s, the procedure should be;
```
xc stop_vm 2
xc reset_vm 2
```
The file systems are synced to prevent corruption as described in issue #58.

Add vm stop/reset commands with file system sync

---

ovl/k8s-cni-bridge/default/etc/init.d/26bridge.rc
ovl/k8s-cni-calico/README.md
ovl/k8s-cni-calico/k8s-cni-calico.sh
ovl/k8s-cni-xcluster/README.md
ovl/mtu/README.md
xcadmin.sh

After retirement of "ovl/k8s-xcluster" there is no need to have two k8s images.
The update in this PR should be backward compatible since the "hd-k8s-xcluster-k8sver.img" is created as a hard-link.
```
cd $XCLUSTER_WORKSPACE/xcluster
ll -i hd-k8s-master.img hd-k8s-xcluster-master.img
20972268 -rw-rw-r-- 4 jenkins uablrek 847M Sep 17 09:20 hd-k8s-master.img
20972268 -rw-rw-r-- 4 jenkins uablrek 847M Sep 17 09:20 hd-k8s-xcluster-master.img
```
same i-node.

Unified k8s image

---

Envsettings
Envsettings.k8s
ovl/private-reg/default/etc/init.d/28private-reg.rc
ovl/private-reg/tar

Also move default dns_spoof settings to Envsettings, this prepares xcluster to be used for testing container networking without k8s.

ovl/private-reg: Use registries.conf

---

ovl/crio/crio.sh

Version $\ge$ 1.28.1 is needed for [User Namespaces](https://kubernetes.io/blog/2023/09/13/userns-alpha/).
Unfortunately the `crun` included in the release bundle is not up to date:
```
vm-002 ~ # crun --version
crun version 1.8.5
commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
rundir: /run/crun
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
```
I expect this to be corrected in later cri-o releases, but until then please use ovl/podman which installs crun 1.9 (at the time of writing).

ovl/crio: update to v1.28.1

---

Envsettings

Works as "cdo \<tab>\<tab>" but you can "grep" the output:
```
lso | grep -i calico
```
Here is a similar function, with a twist. I tend to forget what I was working with at times. The function below lists ovls in "most recent touched" order, use for instance with `lsot | head -10`. I didn't include it to avoid implying that others are as demented as I :smile: 
```sh
lsot() {
local d arg
for d in $(echo $XCLUSTER_OVLPATH | tr : '\n' | sort | uniq); do
arg="$arg $d/*"
done
ls -dt $arg
}
```

Envsettings: Add an "lso" function

---

Envsettings

Better to get XCLUSTER_OVLPATH from $(xc env).

lso bugfix

---

ovl/k8s-cni-calico/README.md
ovl/k8s-cni-calico/calico-orig.yaml
ovl/k8s-cni-calico/default/etc/kubernetes/calico/calico-vpp-nohuge.yaml
ovl/k8s-cni-calico/default/etc/kubernetes/calico/calico.yaml
ovl/k8s-cni-calico/default/etc/kubernetes/calico/calicoctl.yaml
ovl/k8s-cni-calico/default/etc/kubernetes/calico/install-vpp.yaml
ovl/k8s-cni-calico/default/etc/kubernetes/calico/tigera-operator.yaml
ovl/k8s-cni-calico/k8s-cni-calico.sh
ovl/k8s-cni-calico/tar

And a major clean-up and update of the bpf and vpp backends.
A needed clean-up. Both vpp and bpf backends can be started. Bpf still has severe limitations, but vpp seem to be mostly working, except for https://github.com/projectcalico/calico/issues/8269.

ovl/k8s-cni-calico: updrade to v3.26.4

---

ovl/kubernetes/default/etc/kubernetes/kube-proxy.config

Needed to support the new "nftables" proxier, which is released as alpha with feature-gate NFTablesProxyMode=true in K8s v1.29.
Please see https://github.com/kubernetes/kubernetes/pull/121046 for the release note.
The `kube-proxy.config` seem to be backward compatible, at least with K8s v1.28, meaning that parsing is permissive rather than "strict", which would reject unknown yaml items.
On K8s $\ge$ v1.29, test with:
```
cdo test-template
xcluster_FEATURE_GATES=NFTablesProxyMode=true xcluster_PROXY_MODE=nftables \
./test-template.sh test --no-stop basic > $log
```

ovl/kubernetes: renew kube-proxy.config

---

ovl/containerd/README.md
ovl/containerd/containerd.sh
ovl/containerd/default/etc/init.d/32cri-plugin.rc

This is a major version step, and config is completely different. The version is still 1.7.11 by default, but v2.0.0-beta.2 works.
It looks like all support for 1.x versions will be dropped when 2.0 is released. This [took a while to get right](https://github.com/containerd/containerd/issues/9886).

ovl/containerd: prepare for version 2.0

---

ovl/kubernetes/default/etc/init.d/30kube-prep.rc
ovl/kubernetes/default/etc/init.d/31kube-master.rc

Configure the Aggregation Layer and extension api-server. Needed to make the metrics-server work.
To test, please see https://github.com/uablrek/xcluster-ovls/tree/main/k8s-metrics-server
NOTE: The k8s-metrics-server does currently not work with k8s v1.30.0-rc.x and crio v1.28.1. Use containerd or an older K8s

ovl/kubernetes: add more options to the api-server

---

ovl/containerd/default/etc/init.d/32cri-plugin.rc
ovl/crio/README.md
ovl/crio/crio.sh
ovl/crio/default/etc/init.d/32cri-plugin.rc

A _fairly_ straight-forward upgrade. The binaries are now prefixed with "crio-", e.g. "crio-crun". Please see the README.md.

ovl/crio: upgrade to 1.29.2

---

ovl/k8s-cni-cilium/README.md
ovl/k8s-cni-cilium/default/etc/kubernetes/load/quick-install.yaml

No problems found.
Added helm option
```
--set cni.exclusive=false
```
Without this, cilium restores itself as primary cni-plugin and thus disables `multus`. Example:
```
05-cilium.conflist         10-multus.conf.cilium_bak  multus.d/            whereabouts.d/
```

ovl/k8s-cni-cilium: upgrade to v1.15.4

---

ovl/template-k8s/template-k8s.sh
ovl/template/template.sh
ovl/test/README.md

* remove the never-used `dbg()` function
* Refactor `cmd_env()`, and call it by default
* Refactor `cmd_test()`
* Add `--log=`, or `export __log=`. To use `> $log` still work, but is considered obsolete
* Work-around to allow default setting of `$__nvm` in `cmd_env()`
* Export options specified on the command line ($long_opts)
* Fix indentation
* Template for the `test_default()` function. Encouraged to simplify CI
* Handle `--cni=`. Also encouraged to simplify CI
* Special handling of `--cni=cilium`

Update template ovls

---

config/busybox-1.36.1

Some installers uses "command -v" to check the presence of a command
Required for [ovl/k0s](https://github.com/uablrek/xcluster-ovls/tree/main/k0s).

Enable the "command" command in busybox

---

ovl/test/default/usr/lib/xctest

Some K8s installers like k0s and k3s uses something like "k0s kubectl" instead of calling kubectl directly

Use $kubectl instead of kubectl in tests

---

image/rootfs/etc/init.d/rcS

Some programs need these links
Notable `nftables-1.0.9` which breaks proxy-mode=nftables without `/dev/stdin`, but I assume there are others.

Add /dev/std* links

---

ovl/iptools/iptools.sh

It's time. New versions:
```
> ./iptools.sh versions
libmnl=1.0.5
libnftnl=1.2.6
iptables=1.8.10
nftables=1.0.9
libnfnetlink=1.0.1
libnetfilter_acct=1.0.3
libnetfilter_cttimeout=1.0.1
libnetfilter_conntrack=1.0.9
libnetfilter_cthelper=1.0.1
libnetfilter_log=1.0.2
libnetfilter_queue=1.0.3
conntrack_tools=1.4.8
ipvsadm=1.31
ipset7=7.22
ipset=6.38
iproute2=6.9.0
ulogd=2.0.8
```

ovl/iptools: update versions

---

image/rootfs/init

The boot guard is moved to /initialboot
Fixes: #109

Clean /run on restart

---

ovl/srv6/README.md
ovl/srv6/default/bin/srv6_test
ovl/srv6/srv6.sh

Used hard-coded prefix "1000::1". Also some minor doc corrections, and modernize `srv6-sh`.
I used this in https://github.com/kubernetes-sigs/kube-network-policies/pull/51#issuecomment-2216969955

ovl/srv6: Refresh and use $PREFIX

---

ovl/multus/tar
ovl/multus/test/etc/kubernetes/multus/multus-crd-host-device.yaml
ovl/multus/test/etc/kubernetes/multus/multus-crd-ipvlan.yaml
ovl/multus/test/etc/kubernetes/multus/multus-crd-macvlan.yaml
ovl/qemu-sriov/default/etc/kubernetes/qemu-sriov/net3-nad.yaml

From `v0.8.0` whereabouts fail (pods not starting) unless
```yaml
"enable_overlapping_ranges": false
```
is specified in the NADs. This is reported in https://github.com/k8snetworkplumbingwg/whereabouts/issues/507, and may be fixed, or may not. Anyway, setting this always does no harm.
The whereabouts CRDs are _not_ updated by this PR. The tests now passes with whereabouts `v1.8.0` _and_ `v.0.7.0` (v0.8.0 is backward compatible with old CRDs, at least with enable_overlapping_ranges=false), but if the CRDs are updated `v0.8.0` works but _not_ `v0.7.0` (it's not forward compatible). Eventually the CRDs should be updated.

Multus require enable_overlapping_ranges=false
